export const SNACKBAR_NOTIFICATION_TYPES = {
  SNACKBAR_NOTIFICATION_REQUEST: "SNACKBAR_NOTIFICATION_REQUEST",
  SNACKBAR_NOTIFICATION_SUCCESS: "SNACKBAR_NOTIFICATION_SUCCESS",
  SNACKBAR_NOTIFICATION_CLOSE: "SNACKBAR_NOTIFICATION_CLOSE",
};
